### ISSUE TITLE
Prevent submitting twice to one challenge

### ISSUE THREAD

**Issue by ColemanGariety** [ColemanGariety/OpenHacker#29]

**Comment by cp** [comment]
@JacksonGariety I could do this by validating the form in Rails, but I think you started this in the JS.

**Comment by ColemanGariety** [comment]
No, hitting submit should show you a preview of your entry, that's how we stop it.

~ Jackson Gariety

Code is poetry.
http://jacksongariety.com/
@JacksonGariety

**Comment by cp** [comment]
I don't see what you mean. There's already a tick on the submit form, making sure the entry isn't a dupe.

C

On Apr 25, 2013, at 12:07 AM, "Jackson Gariety" <notifications@github.com<mailto:notifications@github.com>> wrote:

No, hitting submit should show you a preview of your entry, that's how we stop it.

~ Jackson Gariety

Code is poetry.
http://jacksongariety.com/
@JacksonGariety

**Comment by ColemanGariety** [comment]
But that checks if they submit the same repo twice. But it doesn't make sure they can't submit two different repos to the same challenge.

This check needs to be an if statement in the view. If they've already submitted their entry, preview it and let them delete it. Otherwise show the form we have now to submit it.

**Comment by cp** [comment]
Oh, right. I see now. Also, you might want to double check your current code for checking to stop duplicate entries. Not working for me.

C

On Apr 25, 2013, at 12:13 AM, "Jackson Gariety" <notifications@github.com<mailto:notifications@github.com>> wrote:

But that checks if they submit the same repo twice. But it doesn't make sure they can't submit two different repos to the same challenge.

This check needs to be an if statement in the view. If they've already submitted their entry, preview it and let them delete it. Otherwise show the form we have now to submit it.
